let g:which_key_map['k']    = [ ':Bdel',               'Kill Buffer']
let g:which_key_map['b']    = [ ':Buffers!',           'Buffers']
let g:which_key_map['s']    = [ ':CocList -I symbols', 'Symbols']
let g:which_key_map['f']    = [ ':Neoformat',          'NeoFormat']
let g:which_key_map['L']    = [ ':Lines!',             'Lines']
